# Generated by Django 2.2.3 on 2019-07-25 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0002_auto_20190725_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calender',
            name='date',
            field=models.DateField(),
        ),
    ]
