# Generated by Django 2.2.3 on 2019-07-24 07:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked', models.BooleanField(default='False')),
                ('psa_id', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=50)),
                ('user_query', models.CharField(max_length=132)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name_plural': 'Tickets',
            },
        ),
    ]
