# Generated by Django 2.2.3 on 2019-07-25 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leaves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psa_id', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('day', models.CharField(max_length=9)),
                ('holiday_type', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Leaves',
            },
        ),
    ]
